name: catalog_request
run-name: processing catalog request form
on:
  issues:
    types: [opened]

jobs:
  issue_form_test:
    name: test github issue form
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v4

      - uses: ./.github/actions/issue_parser
        id: issue_parser
        with:
          template-path: .github/ISSUE_TEMPLATE/catalog_request_template.yml

      - name: Parse issue form data
        id: parse
#        env:
#          form_data: ${{ steps.issue_parser.outputs.jsonString }}
        run: |
             formdata=${{ steps.issue_parser.outputs.jsonString }}
              echo "$formdata"